### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by traceyvanp** [brandonshin/slackbot-workout#26]
Why am I getting this ValueError?

Traceback (most recent call last):
  File "slackbotExercise.py", line 283, in <module>
    main()
  File "slackbotExercise.py", line 267, in main
    bot = Bot()
  File "slackbotExercise.py", line 25, in **init**
    self.setConfiguration()
  File "slackbotExercise.py", line 55, in setConfiguration
    settings = json.load(f)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/**init**.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by stefan814** [comment]
@traceyvanp, was this issue ever fixed? I'm having the same problem now.

**Comment by traceyvanp** [comment]
It's been a while and not using it anymore, but I think I remember solving it by installing and running it on the next version up of Python.
